# Generated by Django 5.0.6 on 2025-10-01 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('reader', 'Reader'), ('author', 'Author'), ('admin', 'Admin')], default='reader', max_length=10),
        ),
    ]
